spring:
  jpa:
    database: MYSQL
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/aula_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&useTimezone=true&serverTimezone=America/Sao_Paulo
    username: root
    password: 123456
  jackson:
    time-zone: America/Sao_Paulo